#!/bin/bash

echo 'input file name'
read var

echo -e '#include <main.h>\n''#include <stdio.h>\n' > ${var}
echo '/**
* main - Entry Point
* Description: false or true validation
* Return: Always 0 (success)
*/
int main(void)
{

return (0);
} ' >> ${var}
chmod u+x ${var}
vi ${var}
