#!/bin/bash

echo 'input file name'
read var

echo -e '#include <stdlib.h>\n''#include <time.h>\n''#include <stdio.h>\n' > ${var}
echo '/**
* main - Entry Point
* Description: false or true validation
* Return: Always 0 (success)
*/
int main(void)
{
srand(time(0));
n = rand() - RAND_MAX / 2;
your code;
return (0);
} ' >> ${var}
chmod u+x ${var}
vi ${var}
